---
common_timezone: Etc/UTC

common_packages:
  - ca-certificates
  - curl
  - gpg
  - jq
  - vim
  - htop
  - chrony
  - qemu-guest-agent

cluster_hosts:
  - ip: 192.168.1.201
    name: k8s-cp01
  - ip: 192.168.1.202
    name: k8s-w01
  - ip: 192.168.1.203
    name: k8s-w02

# Current Kubernetes minor used by this homelab.
kubernetes_minor_version: "1.37"
