[k8s_control_plane]
k8s-cp01 ansible_host=192.168.1.201 expected_ip=192.168.1.201

[k8s_workers]
k8s-w01 ansible_host=192.168.1.202 expected_ip=192.168.1.202
k8s-w02 ansible_host=192.168.1.203 expected_ip=192.168.1.203

[k8s_cluster:children]
k8s_control_plane
k8s_workers

[k8s_cluster:vars]
ansible_user=devops
ansible_become=true
ansible_become_method=sudo
